### ISSUE TITLE
Selective download addons

### ISSUE THREAD

**Issue by mikehudak** [headswe/Swifty-Issue-Tracker#181]
At the moment user need to download all addons at same time. When user have unstable internet connection and interupt downloading in some wat he need to download all addons again and again.

**Feature Request:**
When opening changelog, pick (checkbox) which addon to download. 
Possible download addons one-by-one.

**Comment by headswe** [comment]
Techincally this was a bug where the download would not be resumed correctly, it is fixed in 2.1.5.6

**Comment by mikehudak** [comment]
deprecated
