### ISSUE TITLE
Request: Load custom Arma launch parameters

### ISSUE THREAD

**Issue by Tapawingo** [headswe/Swifty-Issue-Tracker#241]
A major letdown for me when it comes to Swifty is that Swifty doesn't have any capability for custom launch parameters for Arma. Since it launches the arma executable directly skipping the arma 3 launcher application. I request that launch parameters configured in the Arma launcher to be added to the launch path or to have an additional setting in Swifty to define parameters manually. 

After some quick research i've found that the launchers launch parameters are stored as json in: "%UserProfile%\AppData\Local\Arma 3 Launcher\Parameters.json" for windows users.

**Comment by jonpas** [comment]
![image](https://user-images.githubusercontent.com/7935003/156370891-e7ea3756-b4f9-450c-9f99-0eaf1efbcad9.png)
